DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects CASCADE;

CREATE TABLE projects(
id SERIAL PRIMARY KEY,
project VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
code VARCHAR NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users(
id SERIAL PRIMARY KEY,
project_id INT NOT NULL REFERENCES projects(id),
first VARCHAR(255) NOT NULL,
last VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(100) NOT NULL,
image TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tickets(
id SERIAL PRIMARY KEY,
title TEXT NOT NULL,
project_id INT NOT NULL REFERENCES projects(id),
stage INT NOT NULL DEFAULT 1
);

CREATE TABLE messages(
id SERIAL PRIMARY KEY,
project_id INT NOT NULL REFERENCES projects(id),
poster_id INT NOT NULL REFERENCES users(id),
ticket_id INT NOT NULL REFERENCES tickets(id),
text VARCHAR NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);